### ISSUE TITLE
Error is_file 

### ISSUE THREAD

**Issue by romyandre79** [o2system/o2system#4]
Hi there

I got an E_Warning message after compose and try using nginx web service, php7.3-fpm

the message are :

is_file(): File name is longer than the maximum allowed path length on this platform (2048):

is_file(): open_basedir restriction in effect.

**Comment by steevenz** [comment]
Hi again.. ok.. i'll try to fix it.. can you give more information about what you try to build or execute? and please avoid naming a classnames over 20 characters long

**Comment by romyandre79** [comment]
Step by step to produce the error
1. Composer createproject o2system\o2system
2. Running index.php

then E_Warning message show up

Environment:
1. OS windows
2. web server nginx
3. php 7.3-fpm

**Comment by steevenz** [comment]
Thank you @romyandre79 it's has been solved

**Comment by romyandre79** [comment]
Sori, the error still exists after i recreate project from composer

![image](https://user-images.githubusercontent.com/50945689/83813742-2dd86000-a6e8-11ea-85e3-80db203b5246.png)
